# Generated by Django 2.2 on 2020-12-04 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_slugify_location_on_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='sub_district_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location', to='location.SubDistrictType'),
        ),
    ]
