# Generated by Django 2.2 on 2021-06-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_donorinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorinfo',
            name='is_indian',
            field=models.BooleanField(default=False),
        ),
    ]
