# Generated by Django 2.2 on 2020-12-04 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20201124_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiximagerendition',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='core.AffixImage'),
        ),
    ]
