# Generated by Django 2.2 on 2021-05-24 08:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_color_panel.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201204_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_content',
            field=wagtail.core.fields.StreamField([('banner_block', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(required=True)), ('url', wagtail.core.blocks.URLBlock(required=True)), ('text_color', wagtail_color_panel.blocks.NativeColorBlock(default='#000000')), ('banner_color', wagtail_color_panel.blocks.NativeColorBlock(default='#000000'))]))], blank=True, null=True),
        ),
    ]
