# Generated by Django 2.2 on 2021-06-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_abouttheeditorpage_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abouttheeditorpage',
            name='page_title',
        ),
    ]
