# Generated by Django 2.2 on 2021-06-07 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_abouttheeditorpage_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.AffixImage'),
        ),
    ]
