# Generated by Django 2.2 on 2021-06-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_abouttheeditorpage_language'),
        ('core', '0030_homepage_banner_content'),
    ]

    operations = [
    ]
