# Generated by Django 2.2 on 2020-12-04 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20201124_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleauthors',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles_by_author', to='author.Author'),
        ),
    ]
