# Generated by Django 2.2 on 2021-05-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_auto_20201230_1620'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO article_article_authors (
                article_id,
                author_id,
                sort_order,
                role_id,
                show_in_beginning,
                show_in_end
            )
            SELECT
                article_id,
                author_id,
                (select coalesce(max(sort_order), 0) + 1 from article_article_authors aaa where aaa.article_id = aat.article_id),
                (select id from author_role where name = 'Translator'),
                true,
                true
            FROM
                article_article_translators aat;
        """)
    ]
