# Generated by Django 2.2 on 2020-12-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_auto_20170124_1609'),
        ('article', '0022_auto_20201228_1625'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articleauthors',
            unique_together={('article', 'author', 'role', 'sort_order')},
        ),
    ]
