# Generated by Django 2.2 on 2020-12-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_auto_20170124_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
