# Generated by Django 2.2 on 2020-12-30 09:53

from django.db import migrations, models


def load_initial_roles(apps, schema_editor):
    Role = apps.get_model("author", "Role")
    role1 = Role(id=1, name='Photo')
    role2 = Role(id=2, name='Text')
    role3 = Role(id=3, name='Illustration')
    role4 = Role(id=4, name='Video editor')
    role1.save()
    role2.save()
    role3.save()
    role4.save()

class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_role'),
    ]

    operations = [
        migrations.RunPython(load_initial_roles),
    ]
