# Generated by Django 2.2 on 2020-11-24 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_auto_20190910_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='resourcetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_resourcetag_items', to='taggit.Tag'),
        ),
    ]
